#!/usr/bin/env python3
"""
aafixwidth — Fix CJK width issues in ASCII Art generated by graph-easy.

graph-easy calculates box widths using len() which doesn't account for
wide CJK characters. This filter reads AA text and fixes box borders
so they align correctly in monospace terminals.

Usage:
    graph-easy input.dot | python3 aafixwidth.py
    cat broken-aa.txt | python3 aafixwidth.py
"""

import sys
import re
import unicodedata
from typing import List


# ─────────────────────────────────────────────
# Width calculation (same logic as aatable.py)
# ─────────────────────────────────────────────

_ambiguous_width = 1

ZWJ = '\u200d'


def _is_regional_indicator(cp: int) -> bool:
    return 0x1F1E6 <= cp <= 0x1F1FF


def _is_emoji_modifier(cp: int) -> bool:
    return 0x1F3FB <= cp <= 0x1F3FF


def _is_emoji_base(cp: int) -> bool:
    return (
        0x1F600 <= cp <= 0x1F64F or 0x1F900 <= cp <= 0x1F9FF
        or 0x1FA00 <= cp <= 0x1FA6F or 0x1FA70 <= cp <= 0x1FAFF
        or 0x2600 <= cp <= 0x27BF or 0x1F300 <= cp <= 0x1F5FF
        or 0x1F680 <= cp <= 0x1F6FF or 0x1F1E0 <= cp <= 0x1F1FF
    )


def char_display_width(ch: str) -> int:
    if ch in ('\u200d', '\u200b', '\ufe0f', '\ufe0e'):
        return 0
    cat = unicodedata.category(ch)
    if cat in ('Mn', 'Me', 'Cf'):
        return 0
    eaw = unicodedata.east_asian_width(ch)
    if eaw in ('W', 'F'):
        return 2
    if eaw == 'A':
        return _ambiguous_width
    return 1


def display_width(text: str) -> int:
    return sum(char_display_width(ch) for ch in text)


# ─────────────────────────────────────────────
# Box border detection and fixing
# ─────────────────────────────────────────────

# Box characters used by graph-easy
H_CHARS = set('-=')
V_CHARS = set('|')
CORNER_CHARS = set('+')
BORDER_CHARS = H_CHARS | V_CHARS | CORNER_CHARS


def fix_aa_widths(text: str) -> str:
    """Fix CJK width issues in ASCII art text.

    Strategy: For each line, detect content between box borders ('|')
    and adjust the closing border position based on display width.
    This is simpler and more robust than full box detection.
    """
    lines = text.split('\n')
    if not lines:
        return text

    # Step 1: Find the "columns" structure by analyzing horizontal border lines
    # A border line looks like: +----+----+---+
    column_positions = find_column_positions(lines)

    if not column_positions:
        # No box structure detected, try simple line-by-line fix
        return fix_lines_simple(lines)

    # Step 2: Fix each content line to match the column positions
    fixed_lines = []
    for line in lines:
        if is_horizontal_border(line):
            fixed_lines.append(line)
        else:
            fixed_lines.append(fix_content_line(line, column_positions))

    return '\n'.join(fixed_lines)


def find_column_positions(lines: List[str]) -> List[int]:
    """Find column separator positions from horizontal border lines."""
    for line in lines:
        if is_horizontal_border(line):
            positions = [i for i, ch in enumerate(line) if ch == '+']
            if len(positions) >= 2:
                return positions
    return []


def is_horizontal_border(line: str) -> bool:
    """Check if a line is a horizontal border (+----+----+)."""
    stripped = line.rstrip()
    if not stripped:
        return False
    return all(ch in '+-= ' for ch in stripped) and stripped.count('+') >= 2


def fix_content_line(line: str, column_positions: List[int]) -> str:
    """Fix a content line ('| text | text |') to align with column positions."""
    if '|' not in line:
        return line

    # Split by '|' keeping track of positions
    parts = line.split('|')
    if len(parts) < 3:  # Need at least: empty | content | empty
        return line

    # Rebuild the line with correct padding
    result = parts[0]  # Leading part (before first |)

    for i in range(1, len(parts) - 1):
        content = parts[i]
        result += '|'

        # Calculate how much display space the content takes
        content_display = display_width(content)
        content_len = len(content)

        # The expected char width for this cell
        if i < len(column_positions):
            expected_chars = column_positions[i] - column_positions[i - 1] - 1
        else:
            expected_chars = content_len

        # Width difference due to wide chars
        width_diff = content_display - content_len

        # Adjust: remove extra spaces to compensate for wide chars
        if width_diff > 0 and content.endswith(' ' * width_diff):
            result += content[:-width_diff]
        elif width_diff > 0:
            # Try to trim trailing spaces
            trimmed = content.rstrip(' ')
            needed_padding = max(0, expected_chars - display_width(trimmed) - width_diff)
            result += trimmed + ' ' * needed_padding
        else:
            result += content

    result += '|' + parts[-1] if len(parts) > 1 else ''

    return result


def fix_lines_simple(lines: List[str]) -> str:
    """Simple per-line fix when no box structure is detected.

    For each line with '|' separators, adjust padding so that
    display widths match the byte-width assumptions graph-easy made.
    """
    fixed = []
    for line in lines:
        if '|' not in line or is_horizontal_border(line):
            fixed.append(line)
            continue

        # Find segments between |
        segments = line.split('|')
        new_segments = []
        for seg in segments:
            if not seg:
                new_segments.append(seg)
                continue

            text = seg.rstrip(' ')
            trailing = len(seg) - len(text)
            dw = display_width(text)
            char_len = len(text)
            extra = dw - char_len

            if extra > 0 and trailing >= extra:
                new_segments.append(text + ' ' * (trailing - extra))
            else:
                new_segments.append(seg)

        fixed.append('|'.join(new_segments))

    return '\n'.join(fixed)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description='Fix CJK width issues in ASCII Art (e.g. from graph-easy).',
    )
    parser.add_argument(
        'file', nargs='?', default=None,
        help='Input file (default: stdin)',
    )
    parser.add_argument(
        '--ambiguous-width', '-a', type=int, choices=[1, 2], default=1,
        help='Display width for Ambiguous characters (default: 1)',
    )

    args = parser.parse_args()

    global _ambiguous_width
    _ambiguous_width = args.ambiguous_width

    if args.file:
        with open(args.file, encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    print(fix_aa_widths(text), end='')


if __name__ == '__main__':
    main()
