#!/usr/bin/env python3
"""
aafixwidth — Fix CJK width issues in ASCII Art generated by graph-easy.

graph-easy calculates box widths using len() which doesn't account for
wide CJK characters. This filter reads AA text and fixes box borders
so they align correctly in monospace terminals.

Usage:
    graph-easy input.dot | python3 aafixwidth.py
    cat broken-aa.txt | python3 aafixwidth.py
"""

import sys
import re
from typing import List

# Import shared width utilities (grapheme-cluster-aware East Asian Width)
from _aawidth import display_width, set_ambiguous_width, load_ambiguous_width_from_profile
import _aawidth as _aawidth_mod

# Initialise from calibration profile on import
_aawidth_mod.set_ambiguous_width(_aawidth_mod.load_ambiguous_width_from_profile())


# ─────────────────────────────────────────────
# Box border detection and fixing
# ─────────────────────────────────────────────

# Box characters used by graph-easy
H_CHARS = set('-=')
V_CHARS = set('|')
CORNER_CHARS = set('+')
BORDER_CHARS = H_CHARS | V_CHARS | CORNER_CHARS


def fix_aa_widths(text: str) -> str:
    """Fix CJK width issues in ASCII art text.

    Strategy: For each line, detect content between box borders ('|')
    and adjust the closing border position based on display width.
    This is simpler and more robust than full box detection.
    """
    lines = text.split('\n')
    if not lines:
        return text

    # Step 1: Find the "columns" structure by analyzing horizontal border lines
    # A border line looks like: +----+----+---+
    column_positions = find_column_positions(lines)

    if not column_positions:
        # No box structure detected, try simple line-by-line fix
        return fix_lines_simple(lines)

    # Step 2: Fix each content line to match the column positions
    fixed_lines = []
    for line in lines:
        if is_horizontal_border(line):
            fixed_lines.append(line)
        else:
            fixed_lines.append(fix_content_line(line, column_positions))

    # Step 3: If any content line is wider than the border (CJK overflow),
    # redraw the horizontal borders so the right edge aligns with content.
    fixed_lines = _align_borders_to_content(fixed_lines, column_positions)

    return '\n'.join(fixed_lines)


def _align_borders_to_content(
    lines: List[str], column_positions: List[int]
) -> List[str]:
    """Extend horizontal border lines so they are at least as wide as the
    widest content line, keeping the right border aligned with content.

    Only widens borders; never shrinks them (non-degrading)."""
    border_indices = [
        i for i, ln in enumerate(lines) if is_horizontal_border(ln)
    ]
    if not border_indices:
        return lines
    content_widths = [
        display_width(lines[i])
        for i in range(len(lines))
        if i not in border_indices and lines[i].strip()
    ]
    if not content_widths:
        return lines
    target = max(content_widths)
    for i in border_indices:
        cur = display_width(lines[i])
        if cur >= target:
            continue
        lines[i] = _widen_border(lines[i], target)
    return lines


def _widen_border(line: str, target_width: int) -> str:
    """Widen a horizontal border line to target_width by extending the
    last '-' run so the trailing '+' lands at target_width-1."""
    rstripped = line.rstrip()
    if not rstripped or '+' not in rstripped:
        return line
    last_plus = rstripped.rindex('+')
    head = rstripped[:last_plus]            # e.g. '+-----'
    tail = rstripped[last_plus:]            # '+'
    cur = display_width(rstripped)
    if cur >= target_width:
        return rstripped
    head = head + '-' * (target_width - cur)
    return head + tail


def find_column_positions(lines: List[str]) -> List[int]:
    """Find column separator positions from horizontal border lines."""
    for line in lines:
        if is_horizontal_border(line):
            positions = [i for i, ch in enumerate(line) if ch == '+']
            if len(positions) >= 2:
                return positions
    return []


def is_horizontal_border(line: str) -> bool:
    """Check if a line is a horizontal border (+----+----+)."""
    stripped = line.rstrip()
    if not stripped:
        return False
    return all(ch in '+-= ' for ch in stripped) and stripped.count('+') >= 2


def fix_content_line(line: str, column_positions: List[int]) -> str:
    """Fix a content line ('| text | text |') to align with column positions.

    For each cell, pad with spaces so that the display width equals the
    expected char width derived from the border. When content is already
    wider than the cell (CJK overflow), emit it as-is with no padding so
    callers can detect the overflow and extend the border if needed.
    """
    if '|' not in line:
        return line

    # Split by '|' keeping track of positions
    parts = line.split('|')
    if len(parts) < 3:  # Need at least: empty | content | empty
        return line

    # Rebuild the line with correct padding
    result = parts[0]  # Leading part (before first |)

    for i in range(1, len(parts) - 1):
        content = parts[i]
        result += '|'

        # The expected char width for this cell
        if i < len(column_positions):
            expected_chars = column_positions[i] - column_positions[i - 1] - 1
        else:
            expected_chars = len(content)

        # Pad so display_width(content) == expected_chars. display_width
        # already accounts for CJK double width, so no separate width_diff
        # subtraction is needed (previous code double-subtracted it).
        dw = display_width(content)
        if dw <= expected_chars:
            result += content + ' ' * (expected_chars - dw)
        else:
            # Content wider than the cell: emit as-is (border will be
            # extended separately to keep right border aligned).
            result += content

    result += '|' + parts[-1] if len(parts) > 1 else ''

    return result


def fix_lines_simple(lines: List[str]) -> str:
    """Simple per-line fix when no box structure is detected.

    For each line with '|' separators, adjust padding so that
    display widths match the byte-width assumptions graph-easy made.
    """
    fixed = []
    for line in lines:
        if '|' not in line or is_horizontal_border(line):
            fixed.append(line)
            continue

        # Find segments between |
        segments = line.split('|')
        new_segments = []
        for seg in segments:
            if not seg:
                new_segments.append(seg)
                continue

            text = seg.rstrip(' ')
            trailing = len(seg) - len(text)
            dw = display_width(text)
            char_len = len(text)
            extra = dw - char_len

            if extra > 0 and trailing >= extra:
                new_segments.append(text + ' ' * (trailing - extra))
            else:
                new_segments.append(seg)

        fixed.append('|'.join(new_segments))

    return '\n'.join(fixed)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description='Fix CJK width issues in ASCII Art (e.g. from graph-easy).',
    )
    parser.add_argument(
        'file', nargs='?', default=None,
        help='Input file (default: stdin)',
    )
    parser.add_argument(
        '--ambiguous-width', '-a', type=int, choices=[1, 2], default=None,
        help='Display width for Ambiguous characters (default: from ~/.aatable_profile.json, or 1 for Windows/WSL; use 2 for macOS Terminal)',
    )

    args = parser.parse_args()

    # Override Ambiguous width only when explicitly specified; otherwise keep profile value.
    if args.ambiguous_width is not None:
        _aawidth_mod.set_ambiguous_width(args.ambiguous_width)

    if args.file:
        with open(args.file, encoding='utf-8') as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    print(fix_aa_widths(text), end='')


if __name__ == '__main__':
    main()
